### ISSUE TITLE
Number of Reviews slider in Firefox broken

### ISSUE THREAD

**Issue by paulmelis** [pretalx/pretalx#1728]
### Problem and impact

On the Review > Review page the slider controlling the number of reviews to search on has pretty broken behaviour with Firefox 124.0.1. In my case the review count range is 0 to 3, but moving the lower handle of the range snaps it to the upper handle at 3, while the upper handle can't be moved at all. 

I see no errors in the browser console. On Chrome 123.0.6312.86 on the same system the slider works fine.

### Expected behaviour

Allow the lower and upper slider handles to be manipulated correctly.

### Steps to reproduce

1.
2.
3.
4.

### Screenshots

![Peek 2024-04-03 22-47](https://github.com/pretalx/pretalx/assets/1408287/43790c0a-6a69-4d1c-b54c-55a4dd8b4f1e)

### Browser (software, desktop or mobile?) and version

Firefox 124.0.1

### Operating system, dependency versions

Arch Linux

### Version

2024.1.0

**Comment by rixx** [comment]
Cannot reproduce – possibly used to be a Firefox bug that got fixed in the meantime.

**Comment by paulmelis** [comment]
I still see this with Firefox 131.0.

**Comment by rixx** [comment]
I'm currently testing on Firefox 133, but Firefox is my daily driver and I hadn't been able to reproduce this bug earlier either. Happy to accept a PR with a fix, but as long as I can't reproduce the problem, I can do little more.

**Comment by paulmelis** [comment]
I'll recheck when Firefox 133 comes out, if I still see it then
